import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, ArrowUpRight, Braces, FileCode2, Layers3, Loader2, Play, RefreshCw, Search, X } from 'lucide-react';
import { fetchCapabilities, fetchCapabilityArtifact, triggerReplay } from '../services/api';
import { LifecycleSummary } from './WorkspaceViews';

export function CapabilityRegistryView(){
 const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [artifact,setArtifact]=useState<any>(null);const [member,setMember]=useState('1002');const [running,setRunning]=useState('');const [result,setResult]=useState<any>(null);const [replayError,setReplayError]=useState('');
 const refresh=async(showLoading=true)=>{if(showLoading)setLoading(true);try{setItems(await fetchCapabilities());setError('');}catch(e:any){setError(e.message||'Capability registry unavailable');}finally{if(showLoading)setLoading(false);}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(false),5000);return()=>window.clearInterval(timer);},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.capability_id} ${x.description}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const inspect=async(id:string)=>{setError('');try{setArtifact(await fetchCapabilityArtifact(id));}catch(e:any){setError(e.message||'Artifact could not be loaded');}};
 const replay=async(cap:any)=>{setRunning(cap.capability_id);setReplayError('');setResult(null);try{setResult(await triggerReplay(cap.capability_id,{member_id:member},cap.latest_version));}catch(e:any){setReplayError(e.message||'Replay failed');}finally{setRunning('');}};
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">AUTOMATION / ARTIFACTS</div><h1>Capability registry</h1><p>Reusable, versioned workflows compiled from discovery and executed by deterministic replay.</p></div><button className="button button-secondary" onClick={()=>void refresh()}><RefreshCw size={15} className={loading?'spin':''}/>Refresh registry</button></div>
 {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}</div>}
 <section className="registry-toolbar"><div className="registry-intro"><span className="registry-symbol"><Layers3 size={20}/></span><div><b>{items.length} {items.length===1?'capability':'capabilities'}</b><small>Latest published versions · read only</small></div></div><label className="search-field"><Search size={15}/><input placeholder="Filter capabilities" value={query} onChange={e=>setQuery(e.target.value)}/></label></section>
 {replayError&&<div className="notice notice-danger"><AlertCircle size={16}/>{replayError}<button onClick={()=>setReplayError('')}>Dismiss</button></div>}
 {result&&<section className="panel replay-result"><div className="panel-heading"><div><div className="section-kicker">DETERMINISTIC REPLAY RESULT</div><h2>{result.status?.replace(/_/g, ' ')||'Run returned'}</h2></div><button className="icon-button" aria-label="Dismiss result" onClick={()=>setResult(null)}><X size={16}/></button></div><div className="result-grid"><div className="result-value"><span>Run ID</span><b className="mono">{result.run_id||'Not returned'}</b></div><div className="result-value"><span>Execution mode</span><b>{result.execution_mode||'Deterministic Replay'}</b></div><div className="result-value"><span>LLM decision calls</span><b>{result.llm_decision_calls ?? 0}</b></div></div><pre className="result-json">{JSON.stringify(result.outputs||{},null,2)}</pre></section>}
 {loading&&!items.length?<div className="panel loading-row"><Loader2 className="spin" size={18}/>Loading published capabilities…</div>:filtered.length?<div className="capability-grid">{filtered.map(cap=><article className="panel capability-card" key={cap.capability_id}><div className="cap-card-top"><span className="cap-glyph"><Layers3 size={17}/></span><span className={`status-badge ${cap.is_active===false?'tone-neutral':'tone-success'}`}><i/>{cap.is_active===false?'Inactive':'Active'}</span></div><div className="cap-version">{cap.capability_id} <span>·</span> v{cap.latest_version}</div><h2>{cap.name}</h2><p>{cap.description}</p><div className="cap-metadata"><span><b>Target</b>{cap.target_app}</span><span><b>Published</b>{cap.created_at?new Date(cap.created_at).toLocaleDateString():'—'}</span></div><div className="cap-actions"><button className="button button-secondary" onClick={()=>void inspect(cap.capability_id)}><Braces size={15}/>Inspect artifact</button><button className="button button-primary" disabled={Boolean(running)||cap.is_active===false} onClick={()=>void replay(cap)}>{running===cap.capability_id?<Loader2 size={15} className="spin"/>:<Play size={14} fill="currentColor"/>}{running===cap.capability_id?'Replaying':'Replay'}</button></div></article>)}</div>:<div className="panel"><div className="empty-state"><span className="empty-icon"><Layers3 size={20}/></span><h3>{items.length?'No matching capabilities':'No capabilities published'}</h3><p>{items.length?'Try a different search.':'A validated artifact appears here after a discovery workflow completes successfully.'}</p></div></div>}
 <section className="panel replay-input"><div><div className="section-kicker">SAFE REPLAY INPUT</div><b>Member identifier</b><small>Used as the replay parameter for the read-only demonstration capability.</small></div><input className="text-input mono" aria-label="Replay member identifier" value={member} onChange={e=>setMember(e.target.value)} placeholder="1002"/></section>
 {artifact&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setArtifact(null)}><section className="artifact-modal" role="dialog" aria-modal="true" aria-label="Capability artifact"><header><div><div className="section-kicker">PUBLISHED ARTIFACT</div><h2>{artifact.capability_id} <span>v{artifact.version}</span></h2></div><button className="icon-button" aria-label="Close artifact" onClick={()=>setArtifact(null)}><X size={17}/></button></header><div className="artifact-facts"><span>Target <b>{artifact.target_application}</b></span><span>Steps <b>{artifact.steps?.length||artifact.actions?.length||0}</b></span><span>Success check <b>{artifact.success_condition?.rule_type||'Not defined'}</b></span><span>Source recording <b className="mono">{artifact.source_recording_id||'Not linked'}</b></span></div><pre>{JSON.stringify(artifact,null,2)}</pre></section></div>}
 </div>;
}
