import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Camera, CheckCircle2, Download, FileJson2, FileText, Loader2, Search, ShieldCheck, XCircle } from 'lucide-react';
import { fetchRecording, fetchRecordings, fetchRunDetails, fetchRuns } from '../services/api';

export function EvidenceView({selectedRunId}:{selectedRunId?:string}){
 const [runs,setRuns]=useState<any[]>([]);const [recordings,setRecordings]=useState<any[]>([]);const [recordingDetails,setRecordingDetails]=useState<any>(null);const [active,setActive]=useState(selectedRunId||'');const [details,setDetails]=useState<any>(null);const [tab,setTab]=useState<'timeline'|'screenshots'|'payload'>('timeline');const [query,setQuery]=useState('');const [status,setStatus]=useState('ALL');const [recording,setRecording]=useState('ALL');const [capability,setCapability]=useState('ALL');const [period,setPeriod]=useState('ALL');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(selectedRunId)setActive(selectedRunId);},[selectedRunId]);
 useEffect(()=>{let live=true;const refresh=()=>Promise.all([fetchRuns(),fetchRecordings()]).then(([runData,recordingData])=>{if(!live)return;setRuns(runData);setRecordings(recordingData);setActive(current=>current&&runData.some((r:any)=>r.run_id===current)?current:runData[0]?.run_id||'');}).catch((e:any)=>{if(live)setError(e.message||'Could not load execution history');});void refresh();const timer=window.setInterval(()=>void refresh(),3000);return()=>{live=false;window.clearInterval(timer);};},[]);
 useEffect(()=>{if(recording==='ALL'){setRecordingDetails(null);return;}let live=true;const load=()=>fetchRecording(recording).then(data=>{if(live)setRecordingDetails(data);}).catch(()=>{if(live)setRecordingDetails(null);});setRecordingDetails(null);void load();const timer=window.setInterval(load,2500);return()=>{live=false;window.clearInterval(timer);};},[recording]);
 useEffect(()=>{if(!active){setDetails(null);return;}let live=true;let timer:number|undefined;const load=async()=>{try{const data=await fetchRunDetails(active);if(live)setDetails(data);if(['SUCCESS','BUSINESS_OUTCOME','BLOCKED','FAILED','HARD_FAILURE','RECOVERABLE_ERROR','CANCELLED'].includes(String(data.status).toUpperCase())&&timer)window.clearInterval(timer);}catch(e:any){if(live)setError(e.message||'Could not load run evidence');}finally{if(live)setLoading(false);}};setLoading(!details);setError('');void load();timer=window.setInterval(()=>void load(),2500);return()=>{live=false;if(timer)window.clearInterval(timer);};},[active]);
 const filtered=useMemo(()=>runs.filter(r=>{const replayIds=(recordingDetails?.linked_replay_runs||[]).map((item:any)=>typeof item==='string'?item:item.run_id);const linked=recordingDetails&&(recordingDetails.run_id===r.run_id||replayIds.includes(r.run_id));const age=r.created_at?Date.now()-new Date(r.created_at).getTime():Infinity;const within=period==='ALL'||(period==='24H'&&age<86400000)||(period==='7D'&&age<604800000)||(period==='30D'&&age<2592000000);return(status==='ALL'||r.status===status)&&(recording==='ALL'||linked)&&(capability==='ALL'||r.capability_id===capability)&&within&&`${r.run_id} ${r.goal||''} ${r.capability_id||''}`.toLowerCase().includes(query.toLowerCase());}),[runs,recordingDetails,status,recording,capability,period,query]);
 const download=()=>{if(!details)return;const link=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(details,null,2)],{type:'application/json'}));link.href=url;link.download=`${details.run_id}-evidence.json`;link.click();URL.revokeObjectURL(url);};
 const images=(details?.steps||[]).filter((s:any)=>s.screenshot_path&&s.evidence_available!==false);const missingImages=(details?.steps||[]).some((s:any)=>s.screenshot_path&&s.evidence_available===false);
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">OPERATIONS / PROVENANCE</div><h1>Evidence explorer</h1><p>Execution traces, screenshots, checkpoints, and backend result payloads tied to their source run.</p></div><button className="button button-secondary" onClick={download} disabled={!details}><Download size={15}/>Export run JSON</button></div>
 {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}</div>}
 <div className="evidence-layout"><section className="panel evidence-list"><div className="evidence-list-tools"><label className="search-field"><Search size={15}/><input placeholder="Find run, capability, or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="compact-select" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter evidence by run status"><option value="ALL">All statuses</option>{['SUCCESS','BUSINESS_OUTCOME','BLOCKED','FAILED'].map(s=><option key={s}>{s}</option>)}</select></div><div className="evidence-filter-row"><select className="compact-select" value={recording} onChange={e=>setRecording(e.target.value)} aria-label="Filter by recording"><option value="ALL">All recordings</option>{recordings.map(r=><option key={r.recording_id} value={r.recording_id}>{r.recording_id}</option>)}</select><select className="compact-select" value={capability} onChange={e=>setCapability(e.target.value)} aria-label="Filter by capability"><option value="ALL">All capabilities</option>{Array.from(new Set(runs.map(r=>r.capability_id).filter(Boolean))).map((id:any)=><option key={id} value={id}>{id}</option>)}</select><select className="compact-select" value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Filter by time period"><option value="ALL">Any time</option><option value="24H">Last 24 hours</option><option value="7D">Last 7 days</option><option value="30D">Last 30 days</option></select></div><div className="evidence-run-list">{filtered.map((r:any)=><button key={r.run_id} onClick={()=>setActive(r.run_id)} className={`evidence-run-item ${active===r.run_id?'selected':''}`}><span className="mono">{r.run_id}</span><b>{r.goal||'Workflow execution'}</b><span><i className={`status-mini status-${String(r.status).toLowerCase()}`}/>{String(r.status).replace(/_/g, ' ')}<small>{r.execution_mode} · {r.created_at?new Date(r.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}</small></span></button>)}{!filtered.length&&<div className="list-empty">No run evidence matches the current filters.</div>}</div><div className="run-list-count">{filtered.length} runs</div></section>
 <section className="panel evidence-detail">{loading?<div className="loading-row"><Loader2 size={17} className="spin"/>Loading evidence…</div>:!details?<div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><h3>Select a run</h3><p>Choose a run to inspect the evidence returned by the backend.</p></div>:<><header className="evidence-detail-head"><div><div className="section-kicker">SOURCE RUN <span className="mono">· {details.run_id}</span></div><h2>{details.goal}</h2><div className="detail-meta"><span>{details.execution_mode}</span><i/><span>{details.capability_id?`${details.capability_id} · v${details.capability_version||'—'}`:'No linked capability'}</span><i/><span>{details.status}</span></div></div><div className="evidence-tabs" role="tablist"><button className={tab==='timeline'?'selected':''} onClick={()=>setTab('timeline')}><ActivityIcon/>Trace</button><button className={tab==='screenshots'?'selected':''} onClick={()=>setTab('screenshots')}><Camera size={14}/>Images <small>{images.length}</small></button><button className={tab==='payload'?'selected':''} onClick={()=>setTab('payload')}><FileJson2 size={14}/>Payload</button></div></header>
 {tab==='timeline'&&<div className="evidence-timeline"><div className="trace-event"><span className="trace-event-icon"><ShieldCheck size={15}/></span><div><b>Workflow accepted</b><small>{details.created_at?new Date(details.created_at).toLocaleString():'Timestamp unavailable'} · {details.target_app}</small></div><span className="event-tag">START</span></div>{details.capability_id&&<div className="trace-event"><span className="trace-event-icon"><CheckCircle2 size={15}/></span><div><b>{details.execution_mode==='Deterministic Replay'?'Capability selected':'Capability produced'}</b><small className="mono">{details.capability_id} · v{details.capability_version||'—'}</small></div><span className="event-tag">ARTIFACT</span></div>}{details.steps?.map((s:any)=><div className="trace-event" key={s.step_number}><span className={`trace-event-icon ${s.status==='SUCCESS'?'good':s.status==='FAILED'?'bad':''}`}>{s.status==='SUCCESS'?<CheckCircle2 size={15}/>:<XCircle size={15}/>}</span><div><b>Step {s.step_number} · {s.action_type}</b><small>{s.target_description||'Target not recorded'}{s.duration_ms?` · ${s.duration_ms} ms`:''}{s.error?` · ${s.error}`:''}</small></div><span className="event-tag">{s.status}</span></div>)}<div className={`trace-event final-event ${details.status==='SUCCESS'?'good':details.status==='FAILED'?'bad':''}`}><span className="trace-event-icon">{details.status==='SUCCESS'?<CheckCircle2 size={15}/>:<AlertCircle size={15}/>}</span><div><b>Backend outcome · {details.status}</b><small>{details.error||'Execution status recorded by the workflow service.'}</small></div></div><div className="evidence-output"><div className="section-kicker">STRUCTURED RESULT · REDACTED FIELDS AS RETURNED</div><pre>{JSON.stringify(details.result||{},null,2)}</pre></div></div>}
 {tab==='screenshots'&&<div className="screenshot-grid">{images.length?images.map((s:any)=><article className="screenshot-card" key={s.step_number}><img src={`/evidence/${String(s.screenshot_path).replace(/\\/g,'/').split('evidence/').pop()}`} alt={`Screenshot from step ${s.step_number}`}/><div><b>Step {s.step_number} · {s.action_type}</b><small>{s.target_description||'Execution screenshot'}</small></div></article>):<div className="empty-state"><span className="empty-icon"><Camera size={20}/></span><h3>{missingImages?'Evidence file unavailable':'No screenshots attached'}</h3><p>{missingImages?'A screenshot path was recorded, but its file is missing from local evidence storage.':'This run did not return screenshot paths.'}</p></div>}</div>}
 {tab==='payload'&&<pre className="evidence-payload">{JSON.stringify(details,null,2)}</pre>}</>}</section></div></div>;
}
function ActivityIcon(){return <FileText size={14}/>}
