import { useEffect, useState } from 'react';
import { AlertCircle, Camera, CheckCircle2, Keyboard, Loader2, MousePointer2, Play, RefreshCw, ShieldAlert } from 'lucide-react';
import { fetchHandoffInfo, fetchRuns, resumeWorkflowRun, submitOperatorAction } from '../services/api';

export function HandoffView({runId,onRunCompleted}:{runId:string;onRunCompleted:()=>void}){
 const [runs,setRuns]=useState<any[]>([]);const [active,setActive]=useState(runId);const [handoff,setHandoff]=useState<any>(null);const [latestScreenshot,setLatestScreenshot]=useState('');const [loading,setLoading]=useState(false);const [actionBusy,setActionBusy]=useState(false);const [selector,setSelector]=useState('#confirm-dialog-btn');const [message,setMessage]=useState('');const [error,setError]=useState('');
 const refreshList=async()=>{try{const data=await fetchRuns();setRuns(data.filter((x:any)=>['BLOCKED','AWAITING_HUMAN'].includes(String(x.status).toUpperCase())));}catch(e:any){setError(e.message||'Could not load blocked runs');}};
 const load=async(id=active,showLoading=true)=>{if(!id){setHandoff(null);return;}if(showLoading)setLoading(true);try{setHandoff(await fetchHandoffInfo(id));setError('');}catch(e:any){setHandoff(null);setError(e.message||'No handoff information available');}finally{if(showLoading)setLoading(false);}};
 useEffect(()=>{setActive(runId);setLatestScreenshot('');if(runId)void load(runId);else void refreshList();const timer=window.setInterval(()=>{if(runId)void load(runId,false);else void refreshList();},3000);return()=>window.clearInterval(timer);},[runId]);
 const act=async(type:string,params:Record<string,any>={})=>{if(!active)return;setActionBusy(true);setError('');setMessage('');try{const result=await submitOperatorAction(active,type,params);if(result.screenshot_path)setLatestScreenshot(result.screenshot_path);setMessage(`Operator action recorded: ${type.replace(/_/g, ' ')}.`);await load(active);}catch(e:any){setError(e.message||'Operator action failed');}finally{setActionBusy(false);}};
 const resume=async()=>{if(!active)return;setActionBusy(true);setError('');setMessage('');try{const result=await resumeWorkflowRun(active);setMessage(`Backend checkpoint passed · ${result.status}.`);await load(active);if(result.status==='SUCCESS'||result.status==='BUSINESS_OUTCOME')onRunCompleted();}catch(e:any){setError(e.message||'Resume was not confirmed');}finally{setActionBusy(false);}};
 const blockedRuns=runs;
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">OPERATIONS / OPERATOR QUEUE</div><h1>Human intervention</h1><p>Review a blocked live session, take an explicit operator action, then resume through the backend checkpoint.</p></div><button className="button button-secondary" onClick={()=>active?void load(active):void refreshList()}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button></div>
 {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}<button onClick={()=>active?void load(active):void refreshList()}>Retry</button></div>}
 {!active&&<section className="panel queue-panel"><div className="panel-heading"><div><div className="section-kicker">AWAITING OPERATOR</div><h2>Blocked workflow queue</h2></div><span className={`status-badge ${blockedRuns.length?'tone-blocked':'tone-success'}`}><i/>{blockedRuns.length} awaiting</span></div>{blockedRuns.length?blockedRuns.map(r=><button key={r.run_id} className="queue-run" onClick={()=>{setActive(r.run_id);void load(r.run_id);}}><span className="queue-alert"><AlertCircle size={17}/></span><span><b>{r.goal}</b><small className="mono">{r.run_id} · {r.execution_mode}</small></span><span className="queue-time">{r.created_at?new Date(r.created_at).toLocaleString():''}</span></button>):<div className="empty-state"><span className="empty-icon"><CheckCircle2 size={20}/></span><h3>Operator queue is clear</h3><p>No workflow runs currently report a blocked or awaiting-human state.</p></div>}</section>}
 {active&&<><div className="handoff-alert"><span><ShieldAlert size={20}/></span><div><b>Workflow paused for operator review</b><p>{handoff?.reason||'The backend has requested human intervention.'}</p></div><button className="button button-secondary" onClick={()=>{setActive('');setHandoff(null);setMessage('');setLatestScreenshot('');void refreshList();}}>Back to queue</button></div>
 {loading?<section className="panel loading-row"><Loader2 size={16} className="spin"/>Loading handoff session…</section>:<div className="handoff-layout"><section className="panel session-panel"><div className="panel-heading"><div><div className="section-kicker">PRESERVED BROWSER SESSION</div><h2>Execution surface</h2></div><span className={`status-badge ${handoff?.session_active?'tone-success':'tone-danger'}`}><i/>{handoff?.session_active?'Session active':'Session unavailable'}</span></div>{latestScreenshot||handoff?.screenshot_path?<img className="handoff-screenshot" src={`/evidence/${String(latestScreenshot||handoff.screenshot_path).replace(/\\/g,'/').split('evidence/').pop()}`} alt={latestScreenshot?'Screenshot after operator action':'Screenshot captured when execution was blocked'}/>:<div className="session-placeholder"><Camera size={23}/><b>No session screenshot was returned</b><small>The interface does not fabricate a browser preview. Refresh handoff details to check for evidence.</small></div>}<div className="session-facts"><span><small>RUN ID</small><b className="mono">{active}</b></span><span><small>BLOCKED AT STEP</small><b>{handoff?.step_number??'—'}</b></span><span><small>SESSION STATE</small><b>{handoff?.session_active?'In memory':'Expired or closed'}</b></span></div></section>
 <aside className="panel operator-panel"><div><div className="section-kicker">CONTROLLED ACTIONS</div><h2>Operator controls</h2><p>Actions execute in the preserved session. Resume is accepted only after the backend confirms its checkpoint.</p></div><label className="field-label" htmlFor="operator-selector">Target selector</label><input id="operator-selector" className="text-input mono" value={selector} onChange={e=>setSelector(e.target.value)} disabled={!handoff?.session_active||actionBusy}/><button className="button button-secondary control-button" disabled={!handoff?.session_active||actionBusy||!selector.trim()} onClick={()=>void act('click',{selector})}><MousePointer2 size={15}/>Click selector</button><button className="button button-secondary control-button" disabled={!handoff?.session_active||actionBusy} onClick={()=>void act('press_key',{key:'Enter'})}><Keyboard size={15}/>Press Enter</button><button className="button button-secondary control-button" disabled={!handoff?.session_active||actionBusy} onClick={()=>void act('take_screenshot')}><Camera size={15}/>Capture screenshot</button>{message&&<div className="notice notice-success"><CheckCircle2 size={15}/>{message}</div>}{handoff?.operator_actions?.length>0&&<div className="operator-history"><div className="section-kicker">RECORDED OPERATOR ACTIONS</div>{handoff.operator_actions.map((action:any,index:number)=><div key={index}><b>{String(action.action_type).replace(/_/g,' ')}</b><small>{action.status||'RECORDED'}</small></div>)}</div>}{!handoff?.session_active&&<div className="notice notice-warning"><AlertCircle size={15}/>The live session is unavailable. Actions and resume are disabled.</div>}<button className="button button-primary resume-button" disabled={!handoff?.session_active||actionBusy} onClick={()=>void resume()}>{actionBusy?<Loader2 size={15} className="spin"/>:<Play size={14} fill="currentColor"/>}{actionBusy?'Waiting for backend…':'Resume and verify'}</button><small className="operator-footnote">Resume may fail if the same session does not satisfy the saved verification checkpoint.</small></aside></div>}</>}
 </div>;
}
