import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, ArrowRight, FileCode2, Loader2, RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { fetchRecording, fetchRecordings } from '../services/api';

const tone=(s='')=>s==='PUBLISHED'||s==='VALIDATED'||s==='COMPLETED'?'success':s==='FAILED'||s==='ABORTED'||s==='CANCELLED'?'danger':s==='RECORDING'||s==='CREATED'||s==='RUNNING'||s==='DISCOVERY_COMPLETED'||s==='COMPILED'?'info':'warning';
const terminalRecording=(s='')=>['PUBLISHED','FAILED','BLOCKED','CANCELLED','ABORTED'].includes(s.toUpperCase());
export function RecordingExplorerView(){
 const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState('');const [detail,setDetail]=useState<any>(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState('ALL');const [loading,setLoading]=useState(false);const [detailLoading,setDetailLoading]=useState(false);const [error,setError]=useState('');
 const refresh=async(showLoading=true)=>{if(showLoading)setLoading(true);try{const data=await fetchRecordings();setItems(data);setSelected(current=>current&&data.some((x:any)=>x.recording_id===current)?current:data[0]?.recording_id||'');setError('');}catch(e:any){setError(e.message||'Recording history unavailable');}finally{if(showLoading)setLoading(false);}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(false),2500);return()=>window.clearInterval(timer);},[]);useEffect(()=>{if(!selected){setDetail(null);return;}let live=true;let timer:number|undefined;const load=async()=>{try{const data=await fetchRecording(selected);if(live)setDetail(data);if(terminalRecording(data.status)&&timer)window.clearInterval(timer);}catch(e:any){if(live)setError(e.message||'Recording details unavailable');}finally{if(live)setDetailLoading(false);}};if(!detail)setDetailLoading(true);void load();timer=window.setInterval(()=>void load(),2000);return()=>{live=false;if(timer)window.clearInterval(timer);};},[selected]);
 const filtered=useMemo(()=>items.filter(x=>(filter==='ALL'||x.status===filter)&&`${x.recording_id} ${x.goal} ${x.artifact_id||''}`.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">AUTOMATION / DISCOVERY</div><h1>Recording explorer</h1><p>Trace what discovery observed and did, then follow validated recordings to the capability they produced.</p></div><button className="button button-secondary" onClick={()=>void refresh()}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button></div>
 {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}<button onClick={()=>void refresh()}>Retry</button></div>}
 <div className="recordings-layout"><section className="panel recording-list-panel"><div className="list-tools"><label className="search-field"><Search size={15}/><input placeholder="Search recordings" value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="compact-select" aria-label="Filter recordings by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All states</option>{['CREATED','RECORDING','DISCOVERY_COMPLETED','COMPILED','PUBLISHED','BLOCKED','FAILED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></div><div className="recording-list">{filtered.map(row=><button className={`recording-list-item ${selected===row.recording_id?'selected':''}`} key={row.recording_id} onClick={()=>setSelected(row.recording_id)}><div className="recording-list-top"><span className="mono">{row.recording_id}</span><span className={`status-badge tone-${tone(row.status)}`}><i/>{row.status}</span></div><b>{row.goal||'Untitled discovery'}</b><div className="recording-list-meta"><span>{row.action_count} actions</span><span>{row.target_application}</span></div>{row.artifact_id&&<div className="recording-link"><FileCode2 size={13}/>{row.artifact_id} · v{row.artifact_version}</div>}</button>)}{!filtered.length&&!loading&&<div className="list-empty">{items.length?'No recordings match your filters.':'No discovery recordings yet. A recording is saved when a new workflow enters discovery.'}</div>}{loading&&!items.length&&<div className="loading-row"><Loader2 size={16} className="spin"/>Loading recordings…</div>}</div><div className="run-list-count">{filtered.length} recordings</div></section>
 <section className="panel recording-detail-panel">{detailLoading?<div className="loading-row"><Loader2 size={16} className="spin"/>Loading recording…</div>:!detail?<div className="empty-state"><span className="empty-icon"><Activity size={20}/></span><h3>Select a discovery recording</h3><p>Recorded actions, checkpoints, and linked replay history will appear here.</p></div>:<><header className="recording-detail-head"><div><div className="section-kicker">RECORDING / <span className="mono">{detail.recording_id}</span></div><h2>{detail.goal}</h2><div className="detail-meta"><span>Run <b className="mono">{detail.run_id}</b></span><i/><span>{detail.target_application}</span><i/><span>{detail.started_at?new Date(detail.started_at).toLocaleString():'Time unavailable'}</span><i/><span>{detail.duration_seconds==null?'Duration unavailable':`${detail.duration_seconds.toFixed(1)} sec`}</span></div></div><span className={`status-badge tone-${tone(detail.status)}`}><i/>{detail.status}</span></header>
 {detail.artifact_id&&<div className="recording-artifact-link"><span className="artifact-link-icon"><FileCode2 size={16}/></span><div><small>COMPILED CAPABILITY</small><b>{detail.artifact_id} <span>v{detail.artifact_version}</span></b></div><span className="validated-stamp"><ShieldCheck size={14}/>Validated</span></div>}
 {detail.failure_reason&&<div className="notice notice-danger"><AlertCircle size={15}/><span><b>{detail.error_classification||'Discovery stopped'}:</b> {detail.failure_reason}</span></div>}
 <div className="trace-heading"><div><div className="section-kicker">DISCOVERY TRACE</div><h3>Recorded actions <span className="count-inline">{detail.actions?.length||0}</span></h3></div><span className="mini-tag">CHRONOLOGICAL</span></div>
 <div className="recorded-actions">{(detail.actions||[]).map((item:any,i:number)=><article className="recorded-action" key={`${item.sequence}-${i}`}><div className="action-marker">{item.sequence}</div><div className="action-body"><div className="action-title"><b>{item.action_type}</b><span className="action-validation"><i/>{item.validation||'Recorded'}</span></div><div className="action-target mono">{item.target||'No explicit UI target'}</div>{item.why&&<p>{item.why}</p>}<details><summary>Observations and parameters</summary><div className="observation-grid"><div><small>Before</small><pre>{JSON.stringify(item.observation_before||{},null,2)}</pre></div><div><small>Parameters · sensitive values redacted</small><pre>{JSON.stringify(item.parameters||{},null,2)}</pre></div><div><small>Result and after</small><pre>{JSON.stringify({result:item.result,observation:item.observation_after},null,2)}</pre></div></div></details>{item.evidence_error&&<small>Screenshot unavailable: {item.evidence_error}</small>}{item.screenshot_path&&item.evidence_available===false&&<small>Evidence file is unavailable.</small>}{item.screenshot_path&&item.evidence_available!==false&&<img className="trace-screenshot" src={`/evidence/${String(item.screenshot_path).replace(/\\/g,'/').split('evidence/').pop()}`} alt={`Discovery action ${item.sequence} screenshot`}/>}</div></article>)}</div>
 {detail.events?.length>0&&<><div className="trace-heading"><div><div className="section-kicker">PERSISTED EVENT LOG</div><h3>Observations and provider activity <span className="count-inline">{detail.events.length}</span></h3></div><span className="mini-tag">LIVE</span></div><div className="recorded-actions">{detail.events.map((event:any)=><article className="recorded-action" key={`${event.sequence}-${event.event_type}`}><div className="action-marker">{event.sequence}</div><div className="action-body"><div className="action-title"><b>{event.event_type.replace(/_/g,' ')}</b><span className="action-validation"><i/>{event.created_at?new Date(event.created_at).toLocaleTimeString():''}</span></div>{event.payload?.phase&&<div className="action-target">Step {event.payload.step_number} · {event.payload.phase}</div>}{event.payload?.provider&&<div className="action-target">{event.payload.provider} · {event.payload.model} · {event.payload.status}{event.payload.duration_ms?` · ${event.payload.duration_ms} ms`:''}</div>}{event.payload?.error_code&&<div className="action-target">{event.payload.error_code}</div>}<details><summary>Inspect persisted event</summary><pre>{JSON.stringify(event.payload,null,2)}</pre></details>{event.payload?.evidence_error&&<small>Screenshot unavailable: {event.payload.evidence_error}</small>}{event.evidence_path&&event.evidence_available===false&&<small>Evidence file is unavailable.</small>}{event.evidence_path&&event.evidence_available!==false&&<img className="trace-screenshot" src={`/evidence/${String(event.evidence_path).replace(/\\/g,'/').split('evidence/').pop()}`} alt={`Evidence for event ${event.sequence}`}/>}</div></article>)}</div></>}
 {detail.checkpoints?.length>0&&<div className="checkpoints-box"><div className="section-kicker">CHECKPOINTS</div>{detail.checkpoints.map((c:any,i:number)=><div key={i}><span>{c.sequence??i+1}</span><b>{c.outcome||c.validation||'Checkpoint'}</b><small>{c.reason||c.classification||c.evidence||''}</small></div>)}</div>}
 {detail.linked_replay_runs?.length>0&&<div className="linked-replays"><div className="section-kicker">DOWNSTREAM REPLAYS</div>{detail.linked_replay_runs.map((r:any)=><div key={r.run_id}><span className="mono">{r.run_id}</span><span className={`status-badge tone-${tone(r.status)}`}><i/>{r.status}</span><ArrowRight size={14}/></div>)}</div>}
 </>}</section></div></div>;
}
