import { useEffect, useState } from 'react';
import { Activity, AlertCircle, Bot, CheckCircle2, Database, Globe2, Loader2, RefreshCw, Server, ShieldCheck, Workflow } from 'lucide-react';
import { fetchHealth, fetchSafetyPolicy } from '../services/api';

export function SettingsView(){
 const [health,setHealth]=useState<any>(null);const [policy,setPolicy]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=async()=>{setLoading(true);setError('');try{const [h,p]=await Promise.all([fetchHealth(),fetchSafetyPolicy()]);setHealth(h);setPolicy(p);}catch(e:any){setError(e.message||'System settings could not be loaded');}finally{setLoading(false);}};
 useEffect(()=>{void refresh();},[]);
 const healthTone=(value:any)=>value==='healthy'||value==='online'||value==='ready'||value===true?'good':value===false||value==='offline'||(typeof value==='string'&&value.startsWith('unhealthy'))?'bad':'muted';
 const overallReady=health?.status==='healthy'&&health?.database==='healthy'&&health?.target_application?.status==='online'&&health?.browser_automation?.status==='installed';
 const serviceRows=[{name:'API service',detail:health?.system||'Health endpoint',state:health?.status,icon:Server},{name:'Database',detail:'Persistence connectivity',state:health?.database,icon:Database},{name:'Target application',detail:health?.target_application?.url||'Configured target',state:health?.target_application?.status,icon:Globe2},{name:'Browser runtime',detail:health?.browser_automation?.engine||'Automation surface',state:health?.browser_automation?.status,icon:Workflow},{name:'Discovery provider',detail:'Used only when no matching capability is available',state:health?.mistral_ai?.configured,icon:Bot}];
 return <div className="page-stack"><div className="page-heading"><div><div className="eyebrow">CONFIGURATION / SERVICE HEALTH</div><h1>System settings</h1><p>Read-only view of service readiness, execution defaults, and the server-enforced safety policy.</p></div><button className="button button-secondary" onClick={()=>void refresh()}><RefreshCw size={15} className={loading?'spin':''}/>Refresh status</button></div>{error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}</div>}
 <section className="panel system-health"><div className="panel-heading"><div><div className="section-kicker">LIVE HEALTH CHECK</div><h2>Service readiness</h2></div><span className={`health-summary ${overallReady?'health-good':health?'health-bad':'health-wait'}`}><i/>{loading&&!health?'Checking':overallReady?'Operational':health?'Degraded':'Unavailable'}</span></div><div className="health-list">{serviceRows.map(row=>{const Icon=row.icon;const tone=healthTone(row.state);return <div className="health-row" key={row.name}><span className={`health-icon ${tone}`}><Icon size={17}/></span><div className="health-row-copy"><b>{row.name}</b><small>{row.detail}</small></div><span className={`health-state ${tone}`}>{loading&&!health?<><Loader2 size={13} className="spin"/>Checking</>:row.name==='Discovery provider'?row.state===true?'Configured':row.state===false?'Not configured':row.state||'Unknown':row.state||'Unknown'}</span></div>;})}</div><div className="health-foot"><Activity size={14}/><span>Health data supplied by the backend endpoint. Provider credentials are never displayed.</span><span className="health-version">API v{health?.version||'—'}</span></div></section>
 <div className="settings-grid"><section className="panel settings-card"><div className="settings-card-heading"><span className="settings-icon"><Workflow size={17}/></span><div><div className="section-kicker">EXECUTION DEFAULTS</div><h2>Workflow runtime</h2></div></div><div className="settings-pair"><span>Target application</span><b>{health?.target_application?.url||'Not reported'}</b></div><div className="settings-pair"><span>Browser engine</span><b>{health?.browser_automation?.engine||'Not reported'}</b></div><div className="settings-pair"><span>Replay mode</span><b>Deterministic capability execution</b></div><div className="settings-pair"><span>Discovery provider</span><b>{health?.mistral_ai?.configured===true?'Configured':health?.mistral_ai?.configured===false?'Not configured':'Not reported'}</b></div><p className="settings-caption">Discovery is used only when the router cannot find a compatible saved capability. Replay does not require model decisions.</p></section>
 <section className="panel settings-card safety-card"><div className="settings-card-heading"><span className="settings-icon safe"><ShieldCheck size={17}/></span><div><div className="section-kicker">SERVER ENFORCED</div><h2>Safety policy</h2></div><span className="policy-label"><CheckCircle2 size={13}/>Active</span></div><div className="settings-pair"><span>Risky actions</span><b className={policy?.allow_risky_actions?'policy-risk':'policy-safe'}>{policy?.allow_risky_actions===true?'Allowed by policy':policy?.allow_risky_actions===false?'Blocked by policy':'Not reported'}</b></div><div className="policy-block"><small>ALLOWED HOSTS</small><div className="token-list">{policy?.allowed_domains?.length?policy.allowed_domains.map((x:string)=><code key={x}>{x}</code>):<span className="muted-copy">Not reported</span>}</div></div><div className="policy-block"><small>ALLOWED ROUTES</small><div className="token-list">{policy?.allowed_routes?.length?policy.allowed_routes.map((x:string)=><code key={x}>{x}</code>):<span className="muted-copy">Not reported</span>}</div></div><div className="policy-block"><small>REDACTION RULES</small><ul>{policy?.redaction_rules?.length?policy.redaction_rules.map((x:string)=><li key={x}>{x}</li>):<li>Not reported</li>}</ul></div></section></div>
 </div>;
}
