import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Activity, AlertCircle, ArrowDownRight, ArrowLeftRight, ArrowRight, ArrowUpRight, Check, CheckCircle2, FileSearch, Layers3, Loader2, Play, Plus, RefreshCw, Search, ShieldCheck, Sparkles, Workflow, XCircle } from 'lucide-react';
import { ExecutionResult, fetchCapabilities, fetchHealth, fetchRunDetails, fetchRuns, runWorkflowGoal } from '../services/api';

const statusTone = (status = '') => ({ SUCCESS: 'success', VALIDATED: 'success', COMPLETED: 'success', BUSINESS_OUTCOME: 'warning', BLOCKED: 'blocked', AWAITING_HUMAN: 'blocked', FAILED: 'danger', ABORTED: 'danger', CANCELLED: 'danger', RUNNING: 'info' }[status.toUpperCase()] || 'neutral');
const dateLabel = (value?: string) => value ? new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '—';
const durationLabel = (value?: number | null) => value == null ? '—' : value < 1 ? `${Math.round(value * 1000)} ms` : `${value.toFixed(1)} sec`;
const terminalRun = (status='') => ['SUCCESS','BUSINESS_OUTCOME','BLOCKED','FAILED','HARD_FAILURE','RECOVERABLE_ERROR','CANCELLED'].includes(status.toUpperCase());
function StatusBadge({ status }: { status: string }) { return <span className={`status-badge tone-${statusTone(status)}`}><i/>{status.replace(/_/g, ' ')}</span>; }
function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function EmptyState({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) { return <div className="empty-state"><span className="empty-icon"><FileSearch size={20}/></span><h3>{title}</h3><p>{body}</p>{action}</div>; }

export function DashboardView({ onNavigate, onSelectRun }: { onNavigate: (p: string) => void; onSelectRun: (id: string) => void }) {
  const [runs, setRuns] = useState<any[]>([]); const [caps, setCaps] = useState<any[]>([]); const [health, setHealth] = useState<any>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState('');
  const refresh = async (showLoading = true) => { if(showLoading)setBusy(true); try { const [r,c,h] = await Promise.all([fetchRuns(), fetchCapabilities(), fetchHealth()]); setRuns(r); setCaps(c); setHealth(h); setError(''); } catch (e:any) { setError(e.message || 'Unable to load operational data'); } finally { if(showLoading)setBusy(false); } };
  useEffect(() => { void refresh(); const timer=window.setInterval(()=>void refresh(false),5000); return ()=>window.clearInterval(timer); }, []);
  const blocked = runs.filter(r => ['BLOCKED','AWAITING_HUMAN'].includes(String(r.status).toUpperCase()));
  const operational = health?.status === 'healthy' && health?.database === 'healthy' && health?.target_application?.status === 'online' && health?.browser_automation?.status === 'installed';
  const successes = runs.filter(r => r.status === 'SUCCESS').length;
  const recent = runs.slice(0,5);
  return <div className="page-stack">
    <PageHeading eyebrow="OPERATIONS / OVERVIEW" title="Good morning, Naman" description="A clear view of your automation system, reusable workflows, and operator queue." action={<button className="button button-secondary" onClick={() => void refresh()}><RefreshCw size={15} className={busy ? 'spin' : ''}/> Refresh data</button>}/>
    {error && <div className="notice notice-danger"><AlertCircle size={16}/>{error}<button onClick={() => void refresh()}>Try again</button></div>}
    <section className="overview-banner"><div className="banner-copy"><span className="banner-kicker"><span className={operational ? 'pulse-good' : 'pulse-muted'}/>{operational ? 'ENGINE OPERATIONAL' : health ? 'ENGINE DEGRADED' : 'CONNECTING TO ENGINE'}</span><h2>Automation, with a clear chain of custody.</h2><p>Every goal is routed to a versioned capability or recorded as a new discovery. Replays run against the saved artifact with zero model decisions.</p><button className="button button-light" onClick={() => onNavigate('new')}><Plus size={16}/> Start a workflow <ArrowRight size={15}/></button></div><div className="banner-diagram"><div className="diagram-orbit orbit-a"/><div className="diagram-orbit orbit-b"/><div className="diagram-core"><Workflow size={27}/></div><div className="diagram-node node-one"><Search size={14}/><span>ROUTE</span></div><div className="diagram-node node-two"><Layers3 size={14}/><span>REPLAY</span></div><div className="diagram-node node-three"><ShieldCheck size={14}/><span>VERIFY</span></div><div className="diagram-caption">CONTROLLED EXECUTION</div></div><div className="banner-index">01 <span>/ SYSTEM STATUS</span></div></section>
    <section className="stat-grid">
      <Metric icon={<Activity size={16}/>} label="Workflow runs" value={busy ? '—' : runs.length} note="Recorded executions"/>
      <Metric icon={<Layers3 size={16}/>} label="Active capabilities" value={busy ? '—' : caps.filter(c => c.is_active !== false).length} note="Versioned and reusable"/>
      <Metric icon={<AlertCircle size={16}/>} label="Needs attention" value={busy ? '—' : blocked.length} note={blocked.length ? 'Operator action required' : 'No active handoffs'} critical={blocked.length > 0}/>
      <Metric icon={<CheckCircle2 size={16}/>} label="Successful runs" value={busy ? '—' : successes} note="Confirmed by the backend"/>
    </section>
    <div className="overview-grid">
      <section className="panel recent-panel"><div className="panel-heading"><div><div className="section-kicker">EXECUTION HISTORY</div><h2>Recent workflow runs</h2></div><button className="text-action" onClick={() => onNavigate('runs')}>View all <ArrowUpRight size={14}/></button></div>
        {recent.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Workflow</th><th>Mode</th><th>Status</th><th>Started</th><th/></tr></thead><tbody>{recent.map((r:any)=><tr key={r.run_id} onClick={()=>onSelectRun(r.run_id)} tabIndex={0} onKeyDown={(e)=>e.key==='Enter'&&onSelectRun(r.run_id)}><td><b>{r.goal || 'Untitled workflow'}</b><small className="mono">{r.run_id}</small></td><td><span className="mode-label">{r.execution_mode || 'Unknown'}</span></td><td><StatusBadge status={r.status}/></td><td className="muted-cell">{dateLabel(r.created_at)}</td><td><ArrowUpRight size={15} className="row-arrow"/></td></tr>)}</tbody></table></div> : !busy && <EmptyState title="No workflow runs yet" body="Your executions will appear here after the first workflow is submitted." action={<button className="button button-secondary" onClick={()=>onNavigate('new')}>Create a workflow</button>}/>}
        {busy && <div className="loading-row"><Loader2 className="spin" size={17}/>Loading recent runs…</div>}
      </section>
      <section className="panel lifecycle-panel"><div className="panel-heading"><div><div className="section-kicker">HOW APEX WORKS</div><h2>One goal. Two execution paths.</h2></div><span className="mini-tag">SYSTEM FLOW</span></div><p className="panel-intro">The router reuses a matching artifact whenever possible. New tasks enter discovery and become reusable only after validation.</p>
        <div className="path-row"><div className="path-label"><span className="path-number">01</span><b>Existing capability</b><small>Repeatable and model-free</small></div><div className="path-nodes"><FlowNode label="Goal"/><ArrowRight size={14}/><FlowNode label="Lookup"/><ArrowRight size={14}/><FlowNode label="Replay" accent/><ArrowRight size={14}/><FlowNode label="Verify"/></div></div>
        <div className="path-row path-discovery"><div className="path-label"><span className="path-number">02</span><b>New capability</b><small>Learn, validate, reuse</small></div><div className="path-nodes"><FlowNode label="Goal"/><ArrowRight size={14}/><FlowNode label="Discover" warm/><ArrowRight size={14}/><FlowNode label="Compile" warm/><ArrowRight size={14}/><FlowNode label="Replay" accent/></div></div>
        <div className="lifecycle-foot"><ShieldCheck size={15}/><span>Safety policy gates actions. Blocked runs wait for an operator before they can resume.</span></div>
      </section>
    </div>
    <div className="overview-bottom"><div className="service-line"><span className={health?.database === 'healthy' ? 'service-check' : 'service-warn'}><Activity size={14}/></span><div><b>Data service</b><small>{health?.database || 'Checking database'}</small></div></div><div className="service-line"><span className={health?.target_application?.status === 'online' ? 'service-check' : 'service-warn'}><ArrowLeftRight size={14}/></span><div><b>Target application</b><small>{health?.target_application?.status || 'Checking target'}</small></div></div><div className="service-line"><span className={health?.browser_automation?.status === 'installed' ? 'service-check' : 'service-warn'}><Workflow size={14}/></span><div><b>Browser runtime</b><small>{health?.browser_automation?.status || 'Checking runtime'}</small></div></div><button className="text-action" onClick={()=>onNavigate('settings')}>System details <ArrowUpRight size={14}/></button></div>
  </div>;
}
function Metric({ icon, label, value, note, critical }: { icon: React.ReactNode; label: string; value: string | number; note: string; critical?: boolean }) { return <div className={`metric-card ${critical ? 'metric-critical' : ''}`}><div className="metric-top"><span className="metric-icon">{icon}</span><span>{label}</span><ArrowUpRight size={14} className="metric-arrow"/></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>; }
function FlowNode({label,accent,warm}:{label:string;accent?:boolean;warm?:boolean}) { return <span className={`flow-node ${accent?'node-accent':''} ${warm?'node-warm':''}`}><i/>{label}</span>; }

export function NewWorkflowView({ onRunCreated, onNavigateHandoff }: { onRunCreated: (id: string) => void; onNavigateHandoff: (id: string) => void }) {
  const [goal,setGoal] = useState('Find member 1002 and retrieve their savings balance.'); const [member,setMember] = useState('1002'); const [submitting,setSubmitting]=useState(false); const [result,setResult]=useState<ExecutionResult|null>(null); const [error,setError]=useState('');
  const examples = [{label:'Savings balance',goal:'Find member 1002 and retrieve their savings balance.',id:'1002',copy:'Look up an existing member’s savings balance.'},{label:'Member profile',goal:'Find member 1003 and view their profile.',id:'1003',copy:'Retrieve verified profile details.'},{label:'Not found outcome',goal:'Find member 99999 and retrieve their savings balance.',id:'99999',copy:'Inspect a normal business outcome.'}];
  const submit=async(e:FormEvent)=>{e.preventDefault();if(!goal.trim()){setError('Enter a goal to start a workflow.');return;}setSubmitting(true);setError('');setResult(null);try{const data=await runWorkflowGoal({goal:goal.trim(),target_app:'APEX Federal',input_parameters:member.trim()?{member_id:member.trim()}:{}});setResult(data);}catch(err:any){setError(err.message||'Workflow could not be submitted');}finally{setSubmitting(false);}};
  const discovery=result?.execution_mode?.toLowerCase().includes('discovery'); const hasArtifact=Boolean(result?.capability_id && ['SUCCESS','BUSINESS_OUTCOME'].includes(result.status));
  return <div className="page-stack"><PageHeading eyebrow="WORKSPACE / NEW WORKFLOW" title="Describe the task" description="APEX will find a validated capability or discover and record a new workflow."/>
    <div className="composer-layout"><form className="panel workflow-form" onSubmit={submit}><div className="form-title"><span className="form-icon"><Sparkles size={18}/></span><div><h2>Workflow request</h2><p>Runs against the local APEX Federal test application.</p></div></div>
      <label className="field-label" htmlFor="goal">What should APEX do?</label><textarea id="goal" className="text-input goal-input" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe the task in plain language…" rows={4} maxLength={1000}/><div className="field-hint"><span>Be specific about the task and the information you need.</span><span>{goal.length}/1000</span></div>
      <div className="form-row"><div className="field"><label className="field-label" htmlFor="target">Target application</label><div className="select-wrap"><select id="target" className="text-input" value="APEX Federal" disabled><option>APEX Federal</option></select><span className="field-status"><i/>Connected</span></div></div><div className="field"><label className="field-label" htmlFor="member">Member ID <span className="optional">OPTIONAL</span></label><input id="member" className="text-input mono" value={member} onChange={e=>setMember(e.target.value)} placeholder="e.g. 1002" autoComplete="off"/></div></div>
      {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}</div>}
      <div className="form-submit-row"><span className="submission-note"><ShieldCheck size={15}/>Read-only task · Safety policy enforced</span><button className="button button-primary" type="submit" disabled={submitting || !goal.trim()}>{submitting?<><Loader2 size={16} className="spin"/>Submitting…</>:<><Play size={15} fill="currentColor"/>Run workflow</>}</button></div>
    </form>
    <aside className="composer-aside"><section className="panel examples-panel"><div className="section-kicker">START WITH AN EXAMPLE</div><h3>Common tasks</h3><div className="example-list">{examples.map(x=><button className="example-item" key={x.label} onClick={()=>{setGoal(x.goal);setMember(x.id);setResult(null);setError('');}}><span className="example-icon"><ArrowDownRight size={15}/></span><span><b>{x.label}</b><small>{x.copy}</small></span><ArrowRight size={14}/></button>)}</div></section><section className="panel route-note"><span className="route-note-icon"><Workflow size={17}/></span><div><b>How routing works</b><p>A matching capability runs deterministically. If none exists, discovery records actions, compiles an artifact, then verifies it by replay.</p></div></section></aside></div>
    {result&&<section className="panel result-panel"><div className="result-heading"><div><div className="section-kicker">BACKEND CONFIRMED RESULT</div><h2>Execution summary</h2></div><StatusBadge status={result.status}/></div><div className="result-grid"><ResultValue label="Execution mode" value={result.execution_mode}/><ResultValue label="Run ID" value={result.run_id} mono/><ResultValue label="Capability" value={result.capability_id ? `${result.capability_id}${result.capability_version?` · v${result.capability_version}`:''}` : 'Not created'} mono/><ResultValue label="Duration" value={durationLabel(result.duration_seconds)}/></div>
      <LifecycleSummary discovery={Boolean(discovery)} hasArtifact={hasArtifact} status={result.status} recordingId={result.recording_id} replayRunId={result.replay_run_id}/>
      {result.error&&<div className="notice notice-danger"><XCircle size={16}/>{result.error}</div>}
      {result.outputs&&Object.keys(result.outputs).length>0&&<div className="result-output"><div className="section-kicker">RETURNED OUTPUTS</div><pre>{JSON.stringify(result.outputs,null,2)}</pre></div>}
      <div className="result-actions"><button className="button button-secondary" onClick={()=>onRunCreated(result.run_id)}><FileSearch size={15}/>Open run details</button>{result.status==='BLOCKED'&&<button className="button button-danger" onClick={()=>onNavigateHandoff(result.run_id)}>Open operator handoff <ArrowRight size={15}/></button>}</div>
    </section>}
  </div>;
}
function ResultValue({label,value,mono}:{label:string;value:string;mono?:boolean}){return <div className="result-value"><span>{label}</span><b className={mono?'mono':''}>{value}</b></div>}
export function LifecycleSummary({discovery,hasArtifact,status,recordingId,replayRunId}:{discovery:boolean;hasArtifact:boolean;status:string;recordingId?:string;replayRunId?:string}){
 const phases=discovery?[{title:'Capability lookup',state:'done',detail:'No matching artifact; discovery selected.'},{title:'Discovery recording',state:recordingId?'done':'current',detail:recordingId||'Recording identifier not returned.'},{title:'Artifact compilation',state:hasArtifact?'done':status==='FAILED'?'failed':'pending',detail:hasArtifact?'Validated capability stored.':status==='FAILED'?'Compilation not confirmed.':'No compiled artifact confirmed.'},{title:'Deterministic replay',state:replayRunId?'done':status==='SUCCESS'||status==='BUSINESS_OUTCOME'?'done':status==='BLOCKED'?'blocked':'pending',detail:replayRunId|| (status==='SUCCESS'?'Backend returned success.':status==='BUSINESS_OUTCOME'?'Replay completed with a business outcome.':status==='BLOCKED'?'Waiting for operator intervention.':status==='FAILED'?'Not confirmed after the earlier failure.':'Awaiting outcome.')},{title:'Checkpoint outcome',state:status==='SUCCESS'?'done':status==='BUSINESS_OUTCOME'?'outcome':status==='BLOCKED'?'blocked':status==='FAILED'?'failed':'pending',detail:status.replace(/_/g, ' ')}]:[{title:'Capability lookup',state:'done',detail:'Validated capability selected.'},{title:'Discovery & compilation',state:'skipped',detail:'Skipped · existing artifact reused.'},{title:'Deterministic replay',state:status==='SUCCESS'||status==='BUSINESS_OUTCOME'?'done':status==='BLOCKED'?'blocked':status==='FAILED'?'failed':'pending',detail:'Saved artifact executed without LLM decisions.'},{title:'Checkpoint outcome',state:status==='SUCCESS'?'done':status==='BUSINESS_OUTCOME'?'outcome':status==='BLOCKED'?'blocked':status==='FAILED'?'failed':'pending',detail:status.replace(/_/g, ' ')}];
 return <div className="lifecycle-summary"><div className="section-kicker">EXECUTION LIFECYCLE</div><div className="lifecycle-steps">{phases.map((p,i)=><div className={`lifecycle-step state-${p.state}`} key={p.title}><span className="lifecycle-marker">{p.state==='done'?<Check size={13}/>:p.state==='skipped'?<span>–</span>:p.state==='failed'?<XCircle size={14}/>:p.state==='blocked'?<AlertCircle size={14}/>:<span>{i+1}</span>}</span><div><b>{p.title}</b><small>{p.detail}</small></div></div>)}</div></div>
}

export function WorkflowRunsView({initialRunId,onNavigateHandoff}:{initialRunId:string;onNavigateHandoff:(id:string)=>void}){
 const [runs,setRuns]=useState<any[]>([]);const [detail,setDetail]=useState<any>(null);const [selected,setSelected]=useState(initialRunId);const [query,setQuery]=useState('');const [filter,setFilter]=useState('ALL');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=async(showLoading=true)=>{if(showLoading)setLoading(true);try{const data=await fetchRuns();setRuns(data);setSelected(current=>current&&data.some((r:any)=>r.run_id===current)?current:data[0]?.run_id||'');setError('');}catch(e:any){setError(e.message||'Runs could not be loaded');}finally{if(showLoading)setLoading(false);}};
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(false),3000);return()=>window.clearInterval(timer);},[]);useEffect(()=>{if(!selected){setDetail(null);return;}let live=true;let timer:number|undefined;const load=async()=>{try{const data=await fetchRunDetails(selected);if(live)setDetail(data);if(terminalRun(data.status)&&timer)window.clearInterval(timer);}catch(e:any){if(live)setError(e.message||'Run details unavailable');}};void load();timer=window.setInterval(()=>void load(),2500);return()=>{live=false;if(timer)window.clearInterval(timer);};},[selected]);useEffect(()=>{if(initialRunId&&initialRunId!==selected)setSelected(initialRunId);},[initialRunId]);
 const filtered=useMemo(()=>runs.filter(r=>(filter==='ALL'||r.status===filter)&&`${r.goal} ${r.run_id} ${r.capability_id||''}`.toLowerCase().includes(query.toLowerCase())),[runs,filter,query]);
 return <div className="page-stack"><PageHeading eyebrow="WORKSPACE / EXECUTIONS" title="Workflow runs" description="Inspect execution paths, outcomes, artifacts, and step-level evidence." action={<button className="button button-secondary" onClick={()=>void refresh()}><RefreshCw size={15} className={loading?'spin':''}/> Refresh</button>}/>
 {error&&<div className="notice notice-danger"><AlertCircle size={16}/>{error}<button onClick={()=>void refresh()}>Retry</button></div>}
 <div className="run-inspector-layout"><section className="panel run-list-panel"><div className="list-tools"><div className="search-field"><Search size={15}/><input aria-label="Search runs" placeholder="Search runs" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="compact-select" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by status"><option value="ALL">All statuses</option>{['SUCCESS','BUSINESS_OUTCOME','BLOCKED','FAILED','RUNNING','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></div><div className="run-list-head"><span>RUN ID / GOAL</span><span>STATUS</span></div><div className="run-list-scroll">{filtered.map((r:any)=><button key={r.run_id} onClick={()=>setSelected(r.run_id)} className={`run-list-item ${selected===r.run_id?'selected':''}`}><div className="run-list-meta"><span className="mono">{r.run_id}</span><StatusBadge status={r.status}/></div><b>{r.goal||'Untitled workflow'}</b><div className="run-list-foot"><span>{r.execution_mode||'Execution'}</span><span>{dateLabel(r.created_at)}</span></div></button>)}{!filtered.length&&!loading&&<div className="list-empty">No runs match these filters.</div>}{loading&&!runs.length&&<div className="loading-row"><Loader2 size={16} className="spin"/>Loading runs…</div>}</div><div className="run-list-count">{filtered.length} {filtered.length===1?'run':'runs'} shown</div></section>
 <section className="panel run-detail-panel">{!detail?<EmptyState title="Select an execution" body="Choose a run from the list to inspect its lifecycle and outputs."/>:<><div className="run-detail-head"><div><div className="section-kicker">EXECUTION DETAIL <span className="mono">· {detail.run_id}</span></div><h2>{detail.goal}</h2><div className="detail-meta"><span>{detail.target_app}</span><i/><span>{dateLabel(detail.created_at)}</span><i/><span>{durationLabel(detail.duration_seconds)}</span></div></div><StatusBadge status={detail.status}/></div>
 <div className="run-facts"><ResultValue label="Execution mode" value={detail.execution_mode||'—'}/><ResultValue label="Capability" value={detail.capability_id?`${detail.capability_id} · v${detail.capability_version||'—'}`:'No capability'} mono/><ResultValue label="Decision calls" value={detail.execution_mode==='Deterministic Replay'?'0':'See discovery trace'}/></div>
 <LifecycleSummary discovery={String(detail.execution_mode).toLowerCase().includes('discovery')} hasArtifact={Boolean(detail.capability_id&&['SUCCESS','BUSINESS_OUTCOME'].includes(detail.status))} status={detail.status} recordingId={detail.recording_id} replayRunId={detail.linked_replay_runs?.[0]}/>
 {detail.error&&<div className="notice notice-danger"><AlertCircle size={15}/>{detail.error}</div>}
 {detail.status==='BLOCKED'&&<button className="button button-danger" onClick={()=>onNavigateHandoff(detail.run_id)}><AlertCircle size={15}/>Open human intervention</button>}
 <div className="detail-section"><div className="panel-heading"><div><div className="section-kicker">REPLAY TRACE</div><h3>Executed steps <span className="count-inline">{detail.steps?.length||0}</span></h3></div><span className="mini-tag">{detail.execution_mode==='Deterministic Replay'?'DETERMINISTIC':'DISCOVERY'}</span></div>{detail.steps?.length?<div className="step-table-wrap"><table className="data-table step-table"><thead><tr><th>#</th><th>Action</th><th>Target</th><th>Status</th><th>Time</th></tr></thead><tbody>{detail.steps.map((s:any)=><tr key={s.step_number}><td className="mono">{s.step_number}</td><td><b>{s.action_type}</b>{s.error&&<small className="step-error">{s.error}</small>}</td><td className="mono truncate-cell">{s.target_description||'—'}</td><td><StatusBadge status={s.status}/></td><td>{durationLabel(s.duration_ms? s.duration_ms/1000:0)}</td></tr>)}</tbody></table></div>:<p className="muted-copy">No step details were returned for this run.</p>}</div>
 <div className="detail-section outputs-section"><div className="section-kicker">STRUCTURED RESULT</div><pre>{JSON.stringify(detail.result||{},null,2)}</pre></div></>}</section></div></div>;
}
